# Setup
title:        Choral
tagline:      Your cloud orchestrator
baseurl:      ""
paginate:     1
site:
  name: Choral

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
